# Generated by Django 4.0.6 on 2022-08-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaetItem',
            new_name='CartItem',
        ),
    ]
